steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcptestbed-270905/myreact-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcptestbed-270905/myreact-image']
- name: gcr.io/cloud-builders/gke-deploy
  args:
  - run
  - --filename=gke-config.yml
  - --image=gcr.io/gcptestbed-270905/myreact-image:latest
  - --cluster=gkecluster
  - --location=us-central1-f

- name: gcr.io/cloud-builders/kubectl
  args: ['apply', '-f', 'react-service.yaml']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
    - 'CLOUDSDK_CONTAINER_CLUSTER=gkecluster'
